todo/urls.py
from django.urls import path

from .views import (
    EntryCreateView,
    EntryDeleteView,
    EntryEditView,
    MyToDoListView,
    ToDoCreateView,
    ToDoDeleteView,
    ToDoDetailView,
    ToDoEditView,
    ToDoListView,
    UserProfileView,
)

app_name = "todo"

urlpatterns = [
    path("", ToDoListView.as_view(), name="todo-list"),
    path("my/", MyToDoListView.as_view(), name="todo-list-my"),
    path("create/", ToDoCreateView.as_view(), name="todo-create"),
    path("<int:pk>/", ToDoDetailView.as_view(), name="todo-detail"),
    path("<int:pk>/edit/", ToDoEditView.as_view(), name="todo-edit"),
    path("<int:pk>/delete/", ToDoDeleteView.as_view(), name="todo-delete"),
    path("<int:pk>/create_entry/", EntryCreateView.as_view(), name="entry-create"),
    path("entries/<int:pk>/edit/", EntryEditView.as_view(), name="entry-edit"),
    path("entries/<int:pk>/delete/", EntryDeleteView.as_view(), name="entry-delete"),
    path("users/<str:username>/", UserProfileView.as_view(), name="profile"),
]

yyiktodo/urls.py
import debug_toolbar
from django.conf import settings
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls")),
    path("auth/", include("yyik_auth.urls")),
    path("index/", lambda request: redirect("todo:todo-list"), name="index"),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

todo/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator
from django.db import models

User = get_user_model()


class ToDo(models.Model):
    title = models.CharField(max_length=200, default="To-Do List")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="todo_list")
    public = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.title


class Entry(models.Model):
    todo = models.ForeignKey(ToDo, on_delete=models.CASCADE, related_name="entries")
    text = models.CharField(max_length=200, validators=[MinLengthValidator(2)])
    completed = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.todo.save()
        return super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.todo.save()
        return super().delete(*args, **kwargs)

    def __str__(self) -> str:
        return self.text

todo/forms.py
from django import forms

from .models import Entry


class EntryForm(forms.ModelForm):
    text = forms.CharField(
        min_length=2,
        max_length=200,
        label="",
    )

    class Meta:
        model = Entry
        fields = ["text"]

todo/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpRequest
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    FormView,
    ListView,
    UpdateView,
)

from .forms import EntryForm
from .mixins import AddOwnerMixin, OrFilteredMultipleMixin, OrFilteredSingleMixin
from .models import Entry, ToDo

User = get_user_model()


class ToDoListView(OrFilteredMultipleMixin, ListView):
    model = ToDo

    def get_filters(self):
        filters = [Q(public=True)]
        if self.request.user.is_authenticated:
            filters.append(Q(owner=self.request.user))
        return filters

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.select_related("owner")


class MyToDoListView(LoginRequiredMixin, OrFilteredMultipleMixin, ListView):
    model = ToDo

    def get_filters(self):
        return [Q(owner=self.request.user)]

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.select_related("owner")


class UserProfileView(DetailView):
    model = User
    fields = ["username"]
    template_name = "todo/profile.html"
    context_object_name = "profile"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["todo_list"] = ToDo.objects.filter(owner=self.object).filter(  # type: ignore
            public=True
        )
        return context

    def get_object(self, queryset=None):
        queryset = queryset or self.get_queryset()
        return get_object_or_404(queryset, username=self.kwargs["username"])


class ToDoDetailView(OrFilteredSingleMixin, DetailView):
    model = ToDo

    def get_filters(self):
        filters = [Q(public=True)]
        if self.request.user.is_authenticated:
            filters.append(Q(owner=self.request.user))
        return filters

    def get_queryset(self):
        return super().get_queryset().select_related("owner")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if "entry_form" in self.request.session:
            form = EntryForm(self.request.session.pop("entry_form"))
            context["entry_form"] = form
        else:
            context["entry_form"] = EntryForm()
        return context


class ToDoCreateView(AddOwnerMixin, CreateView):
    model = ToDo
    fields = ["title", "public"]
    success_url = reverse_lazy("todo:todo-list")

    def get_success_url(self) -> str:
        return reverse("todo:todo-detail", args=(self.object.pk,))  # type: ignore


class ToDoEditView(LoginRequiredMixin, OrFilteredSingleMixin, UpdateView):
    model = ToDo
    fields = ["title", "public"]

    def get_filters(self):
        return [Q(owner=self.request.user)]

    def get_success_url(self) -> str:
        return reverse("todo:todo-detail", args=(self.object.pk,))


class ToDoDeleteView(LoginRequiredMixin, OrFilteredSingleMixin, DeleteView):
    model = ToDo
    success_url = reverse_lazy("todo:todo-list")

    def get_filters(self):
        return [Q(owner=self.request.user)]


class EntryCreateView(LoginRequiredMixin, FormView):
    form_class = EntryForm

    def get(self, request, pk: int):
        return redirect(reverse("todo:todo-detail", args=(pk,)))

    def post(self, request: HttpRequest, pk: int):
        todo = get_object_or_404(ToDo, pk=pk, owner=request.user)
        form: EntryForm = self.get_form()  # type: ignore
        if form.is_valid():
            entry: Entry = form.save(commit=False)
            entry.todo = todo
            entry.save()
        else:
            request.session["entry_form"] = form.data
        return redirect(reverse("todo:todo-detail", args=(pk,)))


class EntryEditView(LoginRequiredMixin, OrFilteredSingleMixin, UpdateView):
    model = Entry
    fields = ["text", "completed"]
    template_name = "todo/entry_form.html"
    context_object_name = "entry"

    def get_filters(self):
        return [Q(todo__owner=self.request.user)]

    def get_success_url(self) -> str:
        return reverse("todo:todo-detail", args=(self.object.todo.pk,))


class EntryDeleteView(LoginRequiredMixin, OrFilteredSingleMixin, DeleteView):
    model = Entry
    template_name = "todo/entry_confirm_delete.html"
    context_object_name = "entry"

    def get_filters(self):
        return [Q(todo__owner=self.request.user)]

    def get_success_url(self) -> str:
        return reverse("todo:todo-detail", args=(self.object.todo.pk,))

todo/templates/todo/entry_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete To-Do List{% endblock %}

{% block content %}
    <h3>Delete {{ entry }}?</h3>
    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-yellow" value="Save">
            <i class="bi bi-journal-x"></i> Delete
        </button>
        <button type="submit" class="btn btn-outline-yellow" onclick="window.location='{% url 'todo:todo-detail' entry.todo.id %}'; return false;">
            <i class="bi bi-journals"></i> Back
        </button>
    </form>
{% endblock %}

todo/templates/todo/entry_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ entry }}{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-outline-yellow" value="Save">
            <i class="bi bi-journal-check"></i> Save
        </button>
        <button type="submit" class="btn btn-outline-yellow" onclick="window.location='{% url 'todo:todo-detail' entry.todo.id %}'; return false;">
            <i class="bi bi-journals"></i> Back
        </button>
    </form>
{% endblock %}

todo/templates/todo/profile.html
{% extends 'base.html' %}

{% block title %}{{ profile }}'s profile{% endblock %}

{% block content %}
    <h3>{{ profile }}'s public to-do lists:</h3>
    <ul class="list-group bg-dark">
        {% for todo in todo_list %}
            <li class="list-group-item">
                <a href="{% url 'todo:todo-detail' todo.id %}">{{ todo }}</a>
            </li>
        {% endfor %}
    </ul>
    <br>
    <a href="{% url 'todo:todo-list' %}">Back to main page</a>
{% endblock %}

todo/templates/todo/todo_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete To-Do List{% endblock %}

{% block content %}
    <h3>Delete {{ todo }}?</h3>
    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-yellow" value="Save">
            <i class="bi bi-journal-x"></i> Delete
        </button>
        <button type="submit" class="btn btn-outline-yellow" onclick="window.location='{% url 'todo:todo-detail' todo.id %}'; return false;">
            <i class="bi bi-journals"></i> Back
        </button>
    </form>
{% endblock %}

todo/templates/todo/todo_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load todo_tags %}

{% block title %}{{ todo }}{% endblock %}

{% block content %}
    <h2>
        {{ todo }}
        {% if user == todo.owner %}
            <a href="{% url 'todo:todo-edit' todo.id %}"><i class="bi bi-journal-text"></i></a>
            <a href="{% url 'todo:todo-delete' todo.id %}"><i class="bi bi-journal-x"></i></a>
        {% endif %}
    </h2>
    <ul class="list-group bg-dark">
        {% for entry in todo.entries.all %}
            <li class="list-group-item">
                {% if entry.completed %}<strike>{{ entry }}</strike>{% else %}{{ entry }}{% endif %}
                {% if user == todo.owner %}
                    <a href="{% url 'todo:entry-edit' entry.id %}"><i class="bi bi-journal-text"></i></a>
                    <a href="{% url 'todo:entry-delete' entry.id %}"><i class="bi bi-journal-x"></i></a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
    <br>
    {% if user == todo.owner %}
        <form method="POST" action="{% url 'todo:entry-create' todo.id %}">
            {% csrf_token %}
            {% row %}
                {% col %}
                    {{ entry_form.text|as_crispy_field }}
                {% endcol %}
                {% col 'col-sm-2' %}
                    <button class="btn btn-outline-yellow no-wrap" type="submit"><i class="bi bi-journal-plus"></i> Add</button>
                {% endcol %}
            {% endrow %}
        </form>
    {% endif %}
    <a href="{% url 'todo:todo-list' %}">Back</a>
{% endblock %}

todo/templates/todo/todo_form.html
{% extends 'base.html' %}
{% load todo_tags %}
{% load crispy_forms_tags %}

{% block title %}{% if todo %}{{ todo }}{% else %}Create To-Do List{% endif %}{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-outline-yellow">
            <i class="bi bi-journal-check"></i> Save
        </button>
        <button type="submit" class="btn btn-outline-yellow" onclick="window.location='{% get_back_url todo %}'; return false;">
            <i class="bi bi-journals"></i> Back
        </button>
    </form>
{% endblock %}

todo/templates/todo/todo_list.html
{% extends 'base.html' %}
{% load todo_tags %}

{% block title %}To-Do Lists{% endblock %}

{% block content %}
    <h2>To-Do Lists</h2>
    <p>{% toggle_list request.path %}</p>
    <ul class="list-group bg-dark">
    {% for todo in todo_list %}
        <li class="list-group-item">
            {% if user == todo.owner %}
                [<strong>me</strong>]
            {% else %}
                [<a href="{% url 'todo:profile' todo.owner.username %}">{{ todo.owner }}</a>]
            {% endif %}
            <a href="{% url 'todo:todo-detail' todo.id %}">{{ todo }}</a>
        </li>
    {% endfor %}
    </ul>
    <br>
    <button class="btn btn-outline-yellow" onclick="window.location='{% url 'todo:todo-create' %}'"><i class="bi bi-journal-plus"></i> Add To-Do List</button>
{% endblock %}