todo/urls.py
from django.urls import path

from .views import (
    EntryCreateView,
    EntryDeleteView,
    EntryEditView,
    MyToDoListView,
    ToDoCreateView,
    ToDoDeleteView,
    ToDoDetailView,
    ToDoEditView,
    ToDoListView,
    UserProfileView,
)

app_name = "todo"

urlpatterns = [
    path("", ToDoListView.as_view(), name="todo-list"),
    path("my/", MyToDoListView.as_view(), name="todo-list-my"),
    path("create/", ToDoCreateView.as_view(), name="todo-create"),
    path("<int:pk>/", ToDoDetailView.as_view(), name="todo-detail"),
    path("<int:pk>/edit/", ToDoEditView.as_view(), name="todo-edit"),
    path("<int:pk>/delete/", ToDoDeleteView.as_view(), name="todo-delete"),
    path("<int:pk>/create_entry/", EntryCreateView.as_view(), name="entry-create"),
    path("entries/<int:pk>/edit/", EntryEditView.as_view(), name="entry-edit"),
    path("entries/<int:pk>/delete/", EntryDeleteView.as_view(), name="entry-delete"),
    path("users/<str:username>/", UserProfileView.as_view(), name="profile"),
]

yyik_auth/urls.py
from django.urls import path

from .views import LoginView, LogoutView, RegisterView

app_name = "auth"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

yyiktodo/urls.py
import debug_toolbar
from django.conf import settings
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls")),
    path("auth/", include("yyik_auth.urls")),
    path("index/", lambda request: redirect("todo:todo-list"), name="index"),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

templates/base.html
{% extends 'basebase.html' %}
{% load static %}
{% load todo_tags %}

{% block head %}
    <title>{% block title %}Page{% endblock %} — YyikToDo</title>
    <link rel="shortcut icon" type="image/vnd.microsoft.icon" href="{% static 'favicon.ico' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'site.webmanifest' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}


{% block body %}
    <div class="container bg-dark text-light">
        <nav class="navbar navbar-expand-lg navbar-dark bg-black">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'favicon.ico' %}" alt="logo"> <strong>YyikToDo</strong></a> 
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <div class="navbar-nav ms-auto">
                        {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'todo:todo-list-my' %}"><strong>{{ user }}</strong>
                            <a class="nav-link" href="{% url 'auth:logout' %}?next={{ request.path }}">Log Out</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'auth:login' %}?next={{ request.path }}">Log In</a>
                            <a class="nav-link" href="{% url 'auth:register' %}?next={{ request.path }}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
        {% col "col-xl-6 col-lg-7 col-md-10" %}
            {% block content %}
            {% endblock %}
        {% endcol %}
    </div>
{% endblock %}

{% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
{% endblock %}

templates/basebase.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        {% block head %}{% endblock %}
    </head>
    <body class="bg-dark">
        {% block body %}{% endblock %}
        {% block scripts %}{% endblock %}
    </body>
</html>